/**
 * bench/suites.js —— 评测套件清单（声明式）。
 *
 * 一条套件 = 一个已有验证资产的包装。**不改动探针与冒烟本身的契约**，
 * 只负责：给它们端口/数据目录/URL、限时、收日志、解析结果。
 *
 * 占位符由 run.js 解析：
 *   {repo} {port} {dataDir} {webDist} {url} {exe} {python} {electron}
 *   {parityPort} {parityDataDir} {pyPort} {pyDataDir} {goldenDb}
 *
 * requires 取值：gui / reference / llm / mcp / image
 *   —— 不满足时会**跳过并写明原因**，绝不算作通过（报告里 skipped 单独计数）。
 */

const EXE = process.platform === 'win32' ? 'risk-warning-backend.exe' : 'risk-warning-backend'

/** 探针：Python + HTTP，针对运行中的后端 */
const probes = [
  {
    id: 'probe-tables',
    title: '表格对象探针（模板/在线创建/三种写入/勾稽拦截/入库/引擎联动/幂等）',
    kind: 'probe',
    bin: 'python',
    args: ['{repo}/backend/tests/probe_rust_tables.py', '--port', '{port}'],
    parse: 'probe',
    timeoutMs: 180000,
    requires: [],
  },
  {
    id: 'probe-sheets',
    title: '表格导入探针（粘贴 TSV / CSV / XLSX / 长表透视 / 单位识别 / 失败路径）',
    kind: 'probe',
    bin: 'python',
    args: ['{repo}/backend/tests/probe_rust_sheets.py', '--port', '{port}'],
    parse: 'probe',
    timeoutMs: 240000,
    requires: [],
  },
  {
    id: 'probe-workbook',
    title: '工作簿探针（空白表默认/自由命名/多工作表隔离/当前表入库/旧结构归一化）',
    kind: 'probe',
    bin: 'python',
    args: ['{repo}/backend/tests/probe_rust_workbook.py', '--port', '{port}', '--data-dir', '{dataDir}', '--seed-legacy'],
    parse: 'probe',
    timeoutMs: 180000,
    requires: [],
  },
  {
    id: 'probe-media',
    title: '多模态附件探针（上传/去重/读取，跳过真实模型步骤）',
    kind: 'probe',
    bin: 'python',
    args: [
      '{repo}/backend/tests/probe_rust_media.py',
      '--port',
      '{port}',
      '--image',
      '{repo}/desktop/resources/samples/finance_table_demo.png',
      '--no-llm',
    ],
    parse: 'probe',
    timeoutMs: 180000,
    requires: ['image'],
  },
  {
    id: 't5-warning',
    title: 'T5 风险预警层：point-in-time 样本 + 时间切分（ROC-AUC / PR-AUC / Top-K / 提前预警期）',
    kind: 'smoke',
    bin: 'node',
    args: ['{repo}/bench/dataset/t5.js', '--data', '{repo}/bench/dataset/out'],
    parse: 'smoke',
    expectOutput: 'T5: \\{',
    expectReason: 'T5 打分器没有输出汇总行（数据集缺失或脚本失败）',
    timeoutMs: 300000,
    requires: ['dataset'],
  },
  {
    id: 'finrisk-bench',
    title: 'FinRisk-Bench v0.1 能力基准：T1 抽取准确率 / T3 勾稽检出 / T4 指标正确性（真值由生成过程给出）',
    kind: 'smoke',
    bin: 'node',
    // 用旧库夹具单独起一个后端：既不污染主库，又顺带走一遍旧库升级路径
    dataDir: 'golden',
    args: ['{repo}/bench/benchmark/run.js', '--port', '{port}', '--cases', '12'],
    parse: 'smoke',
    expectOutput: 'FINRISK: \\{',
    expectReason: '基准脚本没有输出 FINRISK 汇总行（可能中途失败）',
    timeoutMs: 600000,
    requires: ['golden'],
  },
  {
    id: 'legacy-db-compat',
    title: '旧数据目录兼容：用"升级前"的库跑写路径（会话/表格/企业建档）',
    kind: 'probe',
    bin: 'python',
    // 旧库与"压缩套件的小窗口后端"同理：必须给它一份旧 schema 的库单独起后端
    dataDir: 'golden',
    args: ['{repo}/backend/tests/probe_rust_legacy_db.py', '--port', '{port}'],
    parse: 'probe',
    timeoutMs: 180000,
    requires: ['golden'],
  },
  {
    id: 'probe-finance-golden',
    title: '金标准比对：金融分析（KPI/杜邦/Z·F·M/异常/对标）Rust vs Python 逐点',
    kind: 'probe',
    bin: 'python-httpx',
    args: ['{repo}/backend/tests/probe_rust_finance.py', '--rust-port', '{parityPort}', '--py-port', '{pyPort}', '--ids', '5,2,3,9'],
    parse: 'probe',
    timeoutMs: 240000,
    requires: ['reference'],
  },
  {
    id: 'probe-datasource-golden',
    tier: 'extended',
    title: '金标准比对：公开数据源刷新结果 Rust vs Python',
    kind: 'probe',
    bin: 'python-httpx',
    args: [
      '{repo}/backend/tests/probe_rust_datasource.py',
      '--rust-port',
      '{parityPort}',
      '--py-port',
      '{pyPort}',
      '--golden-db',
      '{pyDataDir}/platform.db',
      '--python-db',
      '{pyDataDir}/platform.db',
    ],
    parse: 'probe',
    timeoutMs: 300000,
    requires: ['reference'],
  },
  {
    id: 'probe-chat-golden',
    tier: 'extended',
    title: '金标准比对：对话链路（含工具调用）Rust vs Python',
    kind: 'probe',
    bin: 'python-httpx',
    args: ['{repo}/backend/tests/probe_rust_chat.py', '--rust-port', '{parityPort}', '--py-port', '{pyPort}'],
    parse: 'probe',
    timeoutMs: 300000,
    requires: ['reference', 'llm'],
  },
  {
    id: 'probe-p4',
    title: 'P4 金标准比对：技能/预设/插件/设置/MCP/会话管理（Rust vs Python）',
    kind: 'probe',
    bin: 'python-httpx',
    args: [
      '{repo}/backend/tests/probe_rust_p4.py',
      '--rust-port',
      '{parityPort}',
      '--py-port',
      '{pyPort}',
      '--write-port',
      '{parityPort}',
      '--skip-env-check',
    ],
    parse: 'probe',
    timeoutMs: 300000,
    requires: ['reference'],
  },
  {
    id: 'probe-p4-risk',
    tier: 'extended',
    title: 'P4 研判：run_risk_analysis 工具 + 按名称研判 + 读侧快照（需真实模型）',
    kind: 'probe',
    bin: 'python-httpx',
    args: ['{repo}/backend/tests/probe_rust_p4_risk.py', '--rust-port', '{parityPort}', '--py-port', '{pyPort}'],
    parse: 'probe',
    timeoutMs: 420000,
    requires: ['reference', 'llm'],
  },
  {
    id: 'probe-p4-tools',
    tier: 'extended',
    title: 'P4 工具装配：内置 + 手搓插件 + MCP 工具是否真的进入模型 tools 数组',
    kind: 'probe',
    bin: 'python-httpx',
    // 探针会自己起 mock LLM，并把"专用后端"的设置指向它 → 必须用独立后端，避免污染其他套件
    backendEnv: { RWP_PREHEAT_ON_STARTUP: 'false' },
    args: ['{repo}/backend/tests/probe_rust_p4_tools.py', '--port', '{port}', '--mock-llm-port', '{altPort}', '--mcp-url', '{mcpUrl}'],
    parse: 'probe',
    timeoutMs: 300000,
    requires: ['mcp'],
  },
  {
    id: 'probe-compaction',
    tier: 'extended',
    title: '上下文压缩探针（小窗口多轮对话，必须真的触发压缩）',
    kind: 'probe',
    bin: 'python-httpx',
    args: ['{repo}/backend/tests/probe_rust_compaction.py', '--port', '{port}', '--turns', '4'],
    // 默认 128k 窗口下这 4 轮压不到阈值 → 给这条套件单独起一个"小窗口"后端
    backendEnv: {
      RWP_LLM_CONTEXT_WINDOW: '4000',
      RWP_COMPACTION_THRESHOLD_RATIO: '0.4',
      RWP_COMPACTION_RETAIN_RATIO: '0.2',
      RWP_COMPACTION_SUMMARY_MAX_TOKENS: '512',
    },
    // 判定必须落在"真的压过"上：用量里的 compact_count > 0（第一轮没东西可折叠是正常的）
    expectOutput: '"compact_count": [1-9]',
    expectReason: '压缩计数为 0：这几轮没有真正触发压缩，等于没测到',
    parse: 'probe',
    timeoutMs: 420000,
    requires: ['llm'],
  },
  {
    id: 'probe-approval',
    tier: 'extended',
    title: '写入审批闸门探针（同意/拒绝两条路径）',
    kind: 'probe',
    bin: 'python-httpx',
    args: ['{repo}/backend/tests/probe_rust_approval.py', '--port', '{port}'],
    parse: 'probe',
    timeoutMs: 300000,
    requires: ['llm'],
  },
]

/** 冒烟：Electron 真实界面（GUI）或独立进程 */
const smokes = [
  {
    id: 'smoke-backend',
    title: '后端二进制冒烟（能启动/建库/健康检查，独立进程，不需要界面）',
    kind: 'smoke',
    bin: 'node',
    args: ['{repo}/desktop/scripts/smoke-backend.js', '--exe', '{exe}', '--data-dir', '{dataDir}/smoke-backend'],
    parse: 'smoke',
    timeoutMs: 120000,
    requires: [],
  },
  {
    id: 'smoke-tables',
    title: 'UI 冒烟：表格列表/新建/编辑/校验链路',
    kind: 'smoke',
    bin: 'electron',
    args: ['{repo}/desktop/scripts/smoke-tables.js'],
    env: { SMOKE_URL: '{url}' },
    parse: 'smoke',
    timeoutMs: 300000,
    requires: ['gui'],
  },
  {
    id: 'smoke-excel',
    title: 'UI 冒烟：Excel 式栅格（公式/填充/行列/撤销重做/排序/导入）',
    kind: 'smoke',
    bin: 'electron',
    args: ['{repo}/desktop/scripts/smoke-excel.js'],
    env: { SMOKE_URL: '{url}' },
    parse: 'smoke',
    timeoutMs: 300000,
    requires: ['gui'],
  },
  {
    id: 'smoke-workbook',
    title: 'UI 冒烟：工作簿（空白表/多工作表/透视表/宏）',
    kind: 'smoke',
    bin: 'electron',
    args: ['{repo}/desktop/scripts/smoke-workbook.js'],
    env: { SMOKE_URL: '{url}' },
    parse: 'smoke',
    timeoutMs: 300000,
    requires: ['gui'],
  },
  {
    id: 'smoke-import',
    title: 'UI 冒烟：导入（CSV/XLSX/粘贴）与预览入库',
    kind: 'smoke',
    bin: 'electron',
    args: ['{repo}/desktop/scripts/smoke-import.js'],
    env: { SMOKE_URL: '{url}' },
    parse: 'smoke',
    timeoutMs: 300000,
    requires: ['gui'],
  },
  {
    id: 'smoke-keep-long',
    title: 'UI 冒烟：长表原样导入 → 透视表 → 插入新工作表',
    kind: 'smoke',
    bin: 'electron',
    args: ['{repo}/desktop/scripts/smoke-keep-long.js'],
    env: { SMOKE_URL: '{url}' },
    parse: 'smoke',
    timeoutMs: 300000,
    requires: ['gui'],
  },
  {
    id: 'verify-grid',
    title: '真事件回归：双击/点击进编辑、点编辑框不关闭、打字不丢字、拖拽不误编辑、最大化还原',
    kind: 'smoke',
    bin: 'electron',
    args: ['{repo}/desktop/scripts/verify-grid.js'],
    env: { SMOKE_URL: '{url}' },
    parse: 'smoke',
    timeoutMs: 240000,
    requires: ['gui'],
  },
  {
    id: 'smoke-finance',
    title: 'UI 冒烟：金融分析面板（KPI/杜邦/Z·F·M）',
    kind: 'smoke',
    bin: 'electron',
    args: ['{repo}/desktop/scripts/smoke-finance.js'],
    env: { SMOKE_URL: '{url}' },
    parse: 'smoke',
    timeoutMs: 300000,
    requires: ['gui'],
  },
  {
    id: 'smoke-chat',
    tier: 'extended',
    title: 'UI 冒烟：对话工作区（流式/工具卡片）',
    kind: 'smoke',
    bin: 'electron',
    args: ['{repo}/desktop/scripts/smoke-chat.js'],
    env: { SMOKE_URL: '{url}' },
    parse: 'smoke',
    timeoutMs: 420000,
    requires: ['gui', 'llm'],
  },
  {
    id: 'smoke-media',
    tier: 'extended',
    title: 'UI 冒烟：图片财报识别填表（需真实模型）',
    kind: 'smoke',
    bin: 'electron',
    args: ['{repo}/desktop/scripts/smoke-media.js'],
    env: { SMOKE_URL: '{url}' },
    parse: 'smoke',
    timeoutMs: 420000,
    requires: ['gui', 'llm'],
  },
]

module.exports = { probes, smokes, EXE }
